// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmhIX7b4BilTuK255MYx435iuZnYKsHK0',
    appId: '1:504430302156:web:93630594b0dd67e6de0369',
    messagingSenderId: '504430302156',
    projectId: 'test-botany-project',
    authDomain: 'test-botany-project.firebaseapp.com',
    storageBucket: 'test-botany-project.appspot.com',
    measurementId: 'G-1S3D4JTCPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcFHkmRuzw_G8aS1PmYDDeqOFB8_JDKh8',
    appId: '1:504430302156:android:20bce53cc05966a1de0369',
    messagingSenderId: '504430302156',
    projectId: 'test-botany-project',
    storageBucket: 'test-botany-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-SX9xlw2eZYYa79al7ZM5o16X5pRgCE',
    appId: '1:504430302156:ios:1e084e80c78dde0cde0369',
    messagingSenderId: '504430302156',
    projectId: 'test-botany-project',
    storageBucket: 'test-botany-project.appspot.com',
    iosClientId: '504430302156-ifj6hm63t2sghscie2hjhj77ses58hhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-SX9xlw2eZYYa79al7ZM5o16X5pRgCE',
    appId: '1:504430302156:ios:1e084e80c78dde0cde0369',
    messagingSenderId: '504430302156',
    projectId: 'test-botany-project',
    storageBucket: 'test-botany-project.appspot.com',
    iosClientId: '504430302156-ifj6hm63t2sghscie2hjhj77ses58hhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourTestProject',
  );
}
